#include <iostream>
#include <fstream>

using namespace std;

const char* fp = "C:/Data/code/ReportGen/spec-report.tex";    

int main() {
    ofstream myfile;
    myfile.open(fp);
    myfile << "\\documentclass{article}\n";
    myfile << "\\title{Robot Specification}\n";
    myfile << "\\author{SpecGen}\n";
    myfile << "\\date{\today}\n";
    
    myfile << "\\begin{document}\n";
    myfile << "\\maketitle\n";
    myfile << "\\section{Introduction}\n";

    myfile << "This document has been auto-generated by SpecGen.\n";
    
    myfile << "\\section{Functional Requirements}\n";
    myfile << "Speed: 4 m/s\nMass: 5 kg\nDimensions: 200 x 150 x 120\n";
    myfile << "\\end{document}\n";

    myfile.close();

    return 0;
}
